### ISSUE TITLE
Crash when using collegiate dictionary

### ISSUE THREAD

**Issue by ahanmal** [gniquil/mw_dictionary_api#1]
When using the gem with the collegiate dictionary, certain words cause a crash. When I try to search "shrift", I get a TypeError:

```
TypeError: can't dup NilClass
    from /Users/ahanmalhotra/Downloads/mw_dictionary_api-master/lib/mw_dictionary_api/parsers/definition_parser.rb:30:in `dup'
    from /Users/ahanmalhotra/Downloads/mw_dictionary_api-master/lib/mw_dictionary_api/parsers/definition_parser.rb:30:in `block in <class:DefinitionParser>'
    from /Users/ahanmalhotra/Downloads/mw_dictionary_api-master/lib/mw_dictionary_api/parsable.rb:45:in `call'
    from /Users/ahanmalhotra/Downloads/mw_dictionary_api-master/lib/mw_dictionary_api/parsable.rb:45:in `block in parse'
    from /Users/ahanmalhotra/Downloads/mw_dictionary_api-master/lib/mw_dictionary_api/parsable.rb:42:in `each'
    from /Users/ahanmalhotra/Downloads/mw_dictionary_api-master/lib/mw_dictionary_api/parsable.rb:42:in `parse'
    from /Users/ahanmalhotra/Downloads/mw_dictionary_api-master/lib/mw_dictionary_api/parsers/entry_parser.rb:49:in `block (2 levels) in <class:EntryParser>'
    from /Users/ahanmalhotra/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.3.1/lib/nokogiri/xml/node_set.rb:237:in `block in each'
    from /Users/ahanmalhotra/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.3.1/lib/nokogiri/xml/node_set.rb:236:in `upto'
    from /Users/ahanmalhotra/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.3.1/lib/nokogiri/xml/node_set.rb:236:in `each'
    from /Users/ahanmalhotra/Downloads/mw_dictionary_api-master/lib/mw_dictionary_api/parsers/entry_parser.rb:45:in `each_slice'
    from /Users/ahanmalhotra/Downloads/mw_dictionary_api-master/lib/mw_dictionary_api/parsers/entry_parser.rb:45:in `each'
    from /Users/ahanmalhotra/Downloads/mw_dictionary_api-master/lib/mw_dictionary_api/parsers/entry_parser.rb:45:in `inject'
    from /Users/ahanmalhotra/Downloads/mw_dictionary_api-master/lib/mw_dictionary_api/parsers/entry_parser.rb:45:in `block in <class:EntryParser>'
    from /Users/ahanmalhotra/Downloads/mw_dictionary_api-master/lib/mw_dictionary_api/parsable.rb:45:in `call'
    from /Users/ahanmalhotra/Downloads/mw_dictionary_api-master/lib/mw_dictionary_api/parsable.rb:45:in `block in parse'
... 2 levels...
    from /Users/ahanmalhotra/Downloads/mw_dictionary_api-master/lib/mw_dictionary_api/parsers/result_parser.rb:11:in `block (2 levels) in <class:ResultParser>'
    from /Users/ahanmalhotra/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.3.1/lib/nokogiri/xml/node_set.rb:237:in `block in each'
    from /Users/ahanmalhotra/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.3.1/lib/nokogiri/xml/node_set.rb:236:in `upto'
    from /Users/ahanmalhotra/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.3.1/lib/nokogiri/xml/node_set.rb:236:in `each'
    from /Users/ahanmalhotra/Downloads/mw_dictionary_api-master/lib/mw_dictionary_api/parsers/result_parser.rb:9:in `inject'
    from /Users/ahanmalhotra/Downloads/mw_dictionary_api-master/lib/mw_dictionary_api/parsers/result_parser.rb:9:in `block in <class:ResultParser>'
    from /Users/ahanmalhotra/Downloads/mw_dictionary_api-master/lib/mw_dictionary_api/parsable.rb:45:in `call'
    from /Users/ahanmalhotra/Downloads/mw_dictionary_api-master/lib/mw_dictionary_api/parsable.rb:45:in `block in parse'
    from /Users/ahanmalhotra/Downloads/mw_dictionary_api-master/lib/mw_dictionary_api/parsable.rb:42:in `each'
    from /Users/ahanmalhotra/Downloads/mw_dictionary_api-master/lib/mw_dictionary_api/parsable.rb:42:in `parse'
    from /Users/ahanmalhotra/Downloads/mw_dictionary_api-master/lib/mw_dictionary_api/result.rb:25:in `parse!'
    from /Users/ahanmalhotra/Downloads/mw_dictionary_api-master/lib/mw_dictionary_api/result.rb:20:in `initialize'
    from /Users/ahanmalhotra/Downloads/mw_dictionary_api-master/lib/mw_dictionary_api/client.rb:64:in `new'
    from /Users/ahanmalhotra/Downloads/mw_dictionary_api-master/lib/mw_dictionary_api/client.rb:64:in `search'
    from (irb):2
```

Here is the xml object from M-W:

``` xml
<?xml version="1.0" encoding="utf-8" ?>
<entry_list version="1.0">
    <entry id="shrift">
        <ew>shrift</ew>
        <subj>RC-1a</subj>
        <hw>shrift</hw>
        <sound>
            <wav>shrift01.wav</wav>
            <wpr>!shrift</wpr>
        </sound>
        <pr>ˈshrift, 
            <it>especially Southern</it> ˈsrift
        </pr>
        <fl>noun</fl>
        <et>Middle English, from Old English 
            <it>scrift,</it> from 
            <it>scrīfan</it> to shrive 
            <ma>shrive</ma>
        </et>
        <def>
            <date>before 12th century</date>
            <sn>1</sn>
            <ssl>archaic</ssl>
            <sn>a</sn>
            <dt>:a remission of sins pronounced by a priest in the sacrament of reconciliation</dt>
            <sn>b</sn>
            <dt>:the act of 
                <fw>shriving</fw> :
                <sx>confession</sx>
            </dt>
            <sn>2</sn>
            <ssl>obsolete</ssl>
            <dt>:
                <sx>confessional</sx>
            </dt>
        </def>
    </entry>
    <entry id="short shrift">
        <ew>short shrift</ew>
        <subj>SY-1</subj>
        <hw>short shrift</hw>
        <fl>noun</fl>
        <def>
            <date>1594</date>
            <sn>1</sn>
            <dt>:barely adequate time for confession before execution</dt>
            <sn>2 a</sn>
            <dt>:little or no attention or consideration 
                <vi>gave the problem 
                    <it>short shrift</it>
                </vi>
            </dt>
            <sn>b</sn>
            <dt>:quick work 
                <un>usually used in the phrase 
                    <it>make short shrift of</it>
                </un>
            </dt>
        </def>
    </entry>
</entry_list>
```

I have a feeling that it is crashing because the sense numbers are letters and numbers. Any ideas on a fix? I tried to add a rescue, but then the definitions key for entries is nil.

Thanks,
Ahan

**Comment by gniquil** [comment]
Hi Ahan,

Thanks for the note. I looked into this and found the problem. If you look at the first entry in your list, inside `<def>`, you see that the first `<sn>` is NOT followed by a `<dt>`. In my code, I assume the `<sn>` and `<dt>` come in pairs. This is why you can the can't dup Nil class error. I should be able to make a fix soon.

**Comment by gniquil** [comment]
@ahanmal 
I just updated the gem. Could you try again and let me know if it works?

**Comment by ahanmal** [comment]
That was fast! Seems to work. Thanks for the fix, I really appreciate it. If I find anything else, I will try to fix it myself. . .

Ahan
